config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :uploads, only: [:index, :new, :create, :destroy]
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :first_name, :last_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    # Add my attributes added to the devise User class
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_filter :authenticate_user!
  # ^^^ not just yet

  def index
    @uploads = Upload.all
    end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(upload_params)

    if @upload.save
      flash[:notice] = "#{@upload.name} has been uploaded."
      redirect_to uploads_path
    else
      render 'new'
    end
  end

  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy
    flash[:notice] = "#{@upload.name} deleted."
    redirect_to uploads_path
  end

  private

  def upload_params
    params.require(:upload).permit(:name, :attachment)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }[flash_type] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat message
             end)
    end
    nil
end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_login_status_section.html.erb
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="#">Navbar</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Features</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Pricing</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>
		<title>Tutorialspoint</title>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		<div class="container-fluid" style="padding-top:20px;">
			<!--  put notices somewhere else in layouts. navbar?-->

			<div class="col-lg-12">
				<!-- <%= flash_messages %> -->
				<%= render partial: 'layouts/login_status_section' %>
				<%= yield %>
			</div>
		</div>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Hello, world!</h1>
  <p class="lead">Welcome to Upldr</p>
  <hr class="m-y-2">
  <p>A file storage alternative.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/uploads" role="button">Start Uploading</a>
  </p>
</div>

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/uploads/destroy.html.erb
<h1>Uploads#destroy</h1>
<p>Find me in app/views/uploads/destroy.html.erb</p>

app/views/uploads/index.html.erb
<% if !flash[:notice].blank? %>
<div class="alert alert-info">
	<%= flash[:notice] %>
</div>
<% end %>

<br/>

<%= link_to "New Upld", new_upload_path, class: "btn btn-primary" %>
<br/>
<br/>
<!-- <div class="table-responsive"> -->

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Download Link</th>
				<th>File extension</th>
				<th>Created at</th>
				<th>Modified</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @uploads.each do |upload| %>

			<tr>
				<td><%= upload.name %></td>
				<td><%= link_to "Download Upld", upload.attachment_url %></td>
				<td><%=File.extname("#{upload.attachment}")%></td>
				<td><%= Date.parse(upload.created_at.to_s).strftime('%m/%d/%Y') %>
					<hr/>
					<%= time_ago_in_words Date.parse(upload.created_at.to_s)%>
					ago
				</td>
				<td class="smalltext"><%= Date.parse(upload.updated_at.to_s).strftime('%m/%d/%Y') %>
					<hr/>
					<%= time_ago_in_words Date.parse(upload.updated_at.to_s)%>
					ago
				</td>
				<td><%= button_to "Delete",  upload, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{upload.name}?" %></td>
			</tr>

			<% end %>
		</tbody>

	</table>
<!-- </div> -->

app/views/uploads/new.html.erb
<% if !@upload.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @upload.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div class = "well">
   <%= form_for @upload, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/uploads/show.html.erb
<h1>Uploads#show</h1>
<p>Find me in app/views/uploads/show.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>